name: stock_trading_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.3
  google_nav_bar: ^5.0.6
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  flutter_screenutil: ^5.9.3
  table_calendar: ^3.1.2
  dropdown_button2: ^2.3.9
  flutter_statusbarcolor_ns: ^0.5.0
  fl_chart: ^0.68.0
  equatable: ^2.0.5
  syncfusion_flutter_gauges: ^26.1.41
  timeline_tile: ^2.0.0
  dotted_border: ^2.1.0
  file_picker: ^8.0.6
  dio: ^5.5.0+1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  permission_handler: ^11.3.1
  win32: ^5.5.4
  jwt_decoder: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  # flutter_launcher_icons: "^0.13.1"

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "images/app_icon_main_low_resolution.png"   # Your main icon
#   adaptive_icon_background: "#ffffff" # Android adaptive icon
#   adaptive_icon_foreground: "images/app_icon_main_low_resolution.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/welcome_to_munafa/
    - images/invest_with_ease/
    - images/profit_and_manage/
    - images/facebook_icon.png
    - images/blank_profile_picture.jpg
    - images/welcome_image.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-Extrabold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Extrabold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin-BETA.ttf
          weight: 100
        - asset: fonts/Inter-ExtraLight-BETA.ttf
          weight: 200
        - asset: fonts/Inter-Light-BETA.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
    - family: landingicons
      fonts:
        - asset: images/icons/landingicons.ttf
    - family: menu
      fonts:
        - asset: images/icons/menu.ttf
    - family: notification
      fonts:
        - asset: images/icons/notification.ttf
    - family: menuicons
      fonts:
        - asset: images/icons/menuicons.ttf
    - family: homeicons
      fonts:
        - asset: images/icons/homeicons.ttf
    - family: marketplaceicons
      fonts:
        - asset: images/icons/marketplaceicons.ttf
    - family: myinvestmentsicons
      fonts:
        - asset: images/icons/myinvestmentsicons.ttf
    - family: dashboard-icons
      fonts:
        - asset: images/icons/dashboard-icons.ttf
    - family: arrow-icons
      fonts:
        - asset: images/icons/arrow-icons.ttf
    - family: summary-icon
      fonts:
        - asset: images/icons/summary-icon.ttf
    - family: active-investment-icon
      fonts:
        - asset: images/icons/active-investment-icon.ttf
    - family: booking-page-icons
      fonts:
        - asset: images/icons/booking-page-icons.ttf
    - family: payment-proof
      fonts:
        - asset: images/icons/payment-proof.ttf
    - family: how-munafa-works-page-icons
      fonts:
        - asset: images/icons/how-munafa-works-page-icons.ttf
    - family: account-page-icon
      fonts:
        - asset: images/icons/account-page-icon.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
